### ISSUE TITLE
non-replicable error during startup

### ISSUE THREAD

**Issue by Juul** [biobricks/bionet-new#26]
Once I was starting the server and reloading the web page just as the server was starting and I got the following error. I have not been able to replicate. It looks like a bug in the `websocket-stream` module.

```
[server] /home/juul/projects/bionet/bionet-new/node_modules/websocket-stream/stream.js:146
[server]     stream.destroy()
[server]            ^
[server] TypeError: stream.destroy is not a function
[server]     at WebSocket.onclose (/home/juul/projects/bionet/bionet-new/node_modules/websocket-stream/stream.js:146:12)
[server]     at WebSocket.onClose (/home/juul/projects/bionet/bionet-new/node_modules/ws/lib/event-target.js:124:16)
[server]     at emitTwo (events.js:131:20)
[server]     at WebSocket.emit (events.js:214:7)
[server]     at WebSocket.emitClose (/home/juul/projects/bionet/bionet-new/node_modules/ws/lib/websocket.js:219:10)
[server]     at _receiver.cleanup (/home/juul/projects/bionet/bionet-new/node_modules/ws/lib/websocket.js:207:39)
[server]     at Receiver.cleanup (/home/juul/projects/bionet/bionet-new/node_modules/ws/lib/receiver.js:572:15)
[server]     at WebSocket.finalize (/home/juul/projects/bionet/bionet-new/node_modules/ws/lib/websocket.js:207:20)
[server]     at emitNone (events.js:111:20)
[server]     at Socket.emit (events.js:208:7)
```

**Comment by Juul** [comment]
fixed by upgrading websocket-stream dependency
